### ISSUE TITLE
Outdated pip requirements

### ISSUE THREAD

**Issue by mattilyra** [okfde/offenesparlament.de#44]
The `pip-requirements` file contains links to outdated packages (like https://github.com/okfn/sqlaload).

**Comment by pudo** [comment]
yes, this code base is horribly outdated, but I don't think it should be maintained any more. instead, we've been trying to split out the individual scrapers into separate repos so they can be more easily re-used here: https://github.com/bundestag

**Comment by mattilyra** [comment]
Ah I see, might be worth adding a comment at the top of the README file so that people know where to look. We did a pydata hackathon this past weekend and at least one person was interested in helping to maintain/update the codebase

**Comment by pudo** [comment]
Yes should add. Obviously, this codebase is open to contributions, but it'll be a significant amount of work to modernise it and I'm not likely to have the time to be a useful assistant in this.

**Comment by dmariassy** [comment]
Hi @pudo, I'm the guy that @mattilyra mentioned as having interest in your project. I totally agree that having a more modular approach would be favourable. I've only just started to familiarise myself with the domain and the project so excuse me if my suggestions turn out to be complete BS...

Anyhow, my idea would be to package the project as a Python library with classes that allow users to access the data through a native Python interface via simple ```imports```. Each data source could be represented as its own Python ```object``` and implement some abstract methods like ```scrape```, ```parse``` and ```store```. To make the project even more configurable, we could also implement a range of backends that would allow users to define where to store the output of their web crawls. Implementing all this should be fairly simple if one follows the Scrapy framework.

IMO, the pros of this approach are:

1. The library could provide a configurable interface for data scientists who are comfortable using Python in their work.
2. The code could still be wrapped into some executable to make it easy for non-programmers to create their own data dump.
3. A transparent and consistent design would make it easier to extend (even to very different contexts, e.g. parliamentary documents from other countries) and maintain the project. Consequently, more people might be interested in contributing.

So this is my current thinking on the topic. I will not have a tremendous amount of time to work on the project but I will try to allocate some time to do some groundwork it in the coming weeks. Let me know what you think of this idea and if there's anything that I forgot to consider in my evaluation!

Cheers!

**Comment by pudo** [comment]
Hey @dmariassy. What you're proposing is basically to re-write all the scrapers to use Scrapy, no? If you want to do that, please be my guest. The existing scripts on the @bundestag organisation work well for me, but I guess Scrapy is more "standard", so it might gain more acceptance with other developers.

If I'm perfectly honest, though, I think that you'd be investing quite a lot of effort into solving an easy problem (scraping the data), while leaving a hard problem unsolved: integrating the data. From my point of view, the most important thing to improve the quality of all these scrapers would be to make their output more linked. This means: make sure that all of the 4 or 5 scrapers identify parliamentarians, procedures and bills by a unique identifier, ideally a URI of some sort.

Also: making sure that the data is available as daily updated scraper dumps somewhere in good formats, e.g. as JSON and XML (Akoma Ntoso) dumps on an S3 buckets.

**Comment by akuckartz** [comment]
Oh @pudo apparently became a proponent of Linked Data - great! Welcome :-)

**Comment by pudo** [comment]
haha, well played, sir. I only said that we need to data integration here. if it comes down to LD tooling, then: so be it. There's probably other solutions, too. Important point is to make sure we can query across.
